In [1]:
import numpy as np

In [5]:
my_list = [1,2,3]
my_2d_list = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_arr = np.array(my_list)
my_2d_arr = np.array(my_2d_list)

In [10]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(5,2)

array([[0.61678039, 0.50269178],
       [0.36965892, 0.10149774],
       [0.30878248, 0.51174726],
       [0.62158114, 0.90687999],
       [0.63393061, 0.13202176]])

In [29]:
np.random.randn(2,3)

array([[-0.43645147,  0.2102318 ,  0.04612305],
       [-0.48685336,  0.58348089,  1.47856939]])

In [31]:
np.random.randint(0,101,(4,5))

array([[15, 75,  8, 82, 70],
       [78,  6, 29, 85, 44],
       [55, 12,  6, 39, 22],
       [ 6, 12,  9, 93, 95]])

In [33]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [35]:
arr = np.arange(0,25)

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
r_arr = np.random.randint(0,101,10)

In [38]:
r_arr.max()

92

In [39]:
r_arr.min()

4

In [40]:
r_arr.argmax()

7

In [41]:
r_arr.argmin()

3

In [42]:
r_arr.dtype

dtype('int32')

In [44]:
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)

In [46]:
arr.shape

(5, 5)